export const theStatics = {
  leftTop: {
    translateX: [-90, 200],
    translateY: [0, -200],
    thecss: {
      position: "absolute",
      top: "7%",
      right: "3%",
      width: "fit-content",
      height: "fit-content",
      zIndex: "1",
      border: "white 2px solid",
    },
    imageWidth: 400,
    imageHeight: 400,
    thesrc: "/images/heeat.jpg",
  },
  rightTop: {
    translateX: [130, -200],
    translateY: [0, -200],
    thecss: {
      position: "absolute",
      top: "5%",
      left: "5%",
      width: "fit-content",
      height: "fit-content",
      zIndex: "1",
      border: "white 2px solid",
    },
    imageWidth: 250,
    imageHeight: 350,
    thesrc: "/images/nickss.jpg",
  },
  leftBottom: {
    translateX: [50, -200],
    translateY: [0, 200],
    thecss: {
      position: "absolute",
      top: "10%",
      left: "5%",
      width: "fit-content",
      height: "fit-content",
      zIndex: "1",
      border: "white 2px solid",
    },
    imageWidth: 300,
    imageHeight: 300,
    thesrc: "/images/Dwyane_Wade_and_LeBron_James.jpg",
  },
  rightBottom: {
    translateX: [-50, 200],
    translateY: [0, 200],
    thecss: {
      position: "absolute",
      top: "5%",
      right: "5%",
      width: "fit-content",
      height: "fit-content",
      zIndex: "1",
      border: "white 2px solid",
    },
    imageWidth: 300,
    imageHeight: 300,
    thesrc: "/images/anthony.jpg",
  },
};
